"""Remove errors

Revision ID: c2ac63c8d24a
Revises: 0fb7a4d63b54
Create Date: 2025-06-18 09:56:38.899105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ac63c8d24a'
down_revision: Union[str, None] = '0fb7a4d63b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friends_contest_id_fkey', 'friends', type_='foreignkey')
    op.drop_column('friends', 'contest_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('contest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('friends_contest_id_fkey', 'friends', 'contests', ['contest_id'], ['id'])
    # ### end Alembic commands ###
