"""add notificated_events table

Revision ID: cc41387a2816
Revises: 65c2e5a8b444
Create Date: 2025-05-27 23:26:43.363753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc41387a2816'
down_revision: Union[str, None] = '65c2e5a8b444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favourite_events_event_id_fkey', 'favourite_events', type_='foreignkey')
    op.create_foreign_key(None, 'favourite_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourite_events', type_='foreignkey')
    op.create_foreign_key('favourite_events_event_id_fkey', 'favourite_events', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
